/**
 * Skills Constants
 *
 * This file contains all available skills organized by category.
 * Used for skill suggestions when sellers add skills to their profile.
 */

export interface SkillCategory {
  id: string;
  name: string;
  icon: string;
  skills: string[];
}

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'graphics-design',
    name: 'Graphics & Design',
    icon: 'palette',
    skills: [
      'Logo Design',
      'Brand Identity',
      'Business Card Design',
      'Illustration',
      'UI/UX Design',
      'Web Design',
      'Mobile App Design',
      'Icon Design',
      'Infographic Design',
      'Packaging Design',
      'Book Cover Design',
      'Album Cover Design',
      'Social Media Design',
      'Banner Design',
      'Flyer Design',
      'Poster Design',
      'Brochure Design',
      'Catalog Design',
      'Menu Design',
      'Resume Design',
      'Presentation Design',
      'T-Shirt Design',
      'Merchandise Design',
      'Character Design',
      'Cartoon & Comics',
      'Pattern Design',
      'Tattoo Design',
      'Storyboard Design',
      'Game Art',
      '3D Modeling',
      '3D Rendering',
      'Product Design',
      'Architectural Design',
      'Interior Design',
      'Fashion Design',
      'Jewelry Design',
      'Print Design',
      'Label Design',
      'Signage Design',
      'Vehicle Wrap Design',
      'Adobe Photoshop',
      'Adobe Illustrator',
      'Adobe InDesign',
      'Figma',
      'Sketch',
      'Adobe XD',
      'Canva',
      'CorelDRAW',
      'Affinity Designer',
      'Procreate',
    ],
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    icon: 'megaphone',
    skills: [
      'Social Media Marketing',
      'Social Media Management',
      'Facebook Marketing',
      'Instagram Marketing',
      'LinkedIn Marketing',
      'Twitter/X Marketing',
      'TikTok Marketing',
      'Pinterest Marketing',
      'YouTube Marketing',
      'Content Marketing',
      'Email Marketing',
      'SEO',
      'Local SEO',
      'Technical SEO',
      'On-Page SEO',
      'Off-Page SEO',
      'Link Building',
      'Keyword Research',
      'SEM',
      'Google Ads',
      'Facebook Ads',
      'Instagram Ads',
      'LinkedIn Ads',
      'PPC Advertising',
      'Display Advertising',
      'Retargeting',
      'Conversion Rate Optimization',
      'Landing Page Optimization',
      'A/B Testing',
      'Marketing Strategy',
      'Brand Strategy',
      'Growth Hacking',
      'Influencer Marketing',
      'Affiliate Marketing',
      'Lead Generation',
      'Marketing Automation',
      'HubSpot',
      'Mailchimp',
      'Klaviyo',
      'Google Analytics',
      'Google Tag Manager',
      'Meta Business Suite',
      'Hootsuite',
      'Buffer',
      'Sprout Social',
      'SEMrush',
      'Ahrefs',
      'Moz',
      'Community Management',
      'Reputation Management',
    ],
  },
  {
    id: 'writing-translation',
    name: 'Writing & Translation',
    icon: 'pencil',
    skills: [
      'Content Writing',
      'Blog Writing',
      'Article Writing',
      'SEO Writing',
      'Copywriting',
      'Sales Copy',
      'Ad Copy',
      'Email Copywriting',
      'Website Copy',
      'Product Descriptions',
      'Technical Writing',
      'Creative Writing',
      'Ghostwriting',
      'Scriptwriting',
      'Speechwriting',
      'Resume Writing',
      'Cover Letter Writing',
      'Grant Writing',
      'Proposal Writing',
      'Business Writing',
      'Academic Writing',
      'Research Writing',
      'White Paper Writing',
      'Case Study Writing',
      'Press Release Writing',
      'Newsletter Writing',
      'Social Media Content',
      'UX Writing',
      'Editing',
      'Proofreading',
      'Translation',
      'Localization',
      'Transcription',
      'Subtitling',
      'Closed Captioning',
      'English Writing',
      'Spanish Translation',
      'French Translation',
      'German Translation',
      'Chinese Translation',
      'Japanese Translation',
      'Korean Translation',
      'Arabic Translation',
      'Portuguese Translation',
      'Italian Translation',
      'Russian Translation',
      'Hindi Translation',
      'Dutch Translation',
      'Legal Writing',
      'Medical Writing',
    ],
  },
  {
    id: 'video-animation',
    name: 'Video & Animation',
    icon: 'video',
    skills: [
      'Video Editing',
      'Video Production',
      'Motion Graphics',
      '2D Animation',
      '3D Animation',
      'Whiteboard Animation',
      'Explainer Videos',
      'Animated Logos',
      'Character Animation',
      'Product Animation',
      'Intro & Outro Videos',
      'Lyric Videos',
      'Music Videos',
      'Documentary',
      'Corporate Videos',
      'Promotional Videos',
      'Social Media Videos',
      'YouTube Videos',
      'TikTok Videos',
      'Instagram Reels',
      'Short Form Content',
      'Live Action Videos',
      'Drone Videography',
      'Real Estate Videos',
      'Event Videography',
      'Wedding Videos',
      'Visual Effects (VFX)',
      'Compositing',
      'Color Grading',
      'Color Correction',
      'Sound Design',
      'Video Thumbnails',
      'Slideshow Videos',
      'Screencasting',
      'Tutorial Videos',
      'E-Learning Videos',
      'Adobe Premiere Pro',
      'Final Cut Pro',
      'DaVinci Resolve',
      'Adobe After Effects',
      'Cinema 4D',
      'Blender',
      'Maya',
      'Lottie Animation',
      'GIF Animation',
      'Stop Motion',
      'Video Ad Creation',
      'Livestreaming',
      'Video SEO',
      'YouTube Optimization',
    ],
  },
  {
    id: 'music-audio',
    name: 'Music & Audio',
    icon: 'music',
    skills: [
      'Music Production',
      'Beat Making',
      'Songwriting',
      'Music Composition',
      'Jingles & Intros',
      'Background Music',
      'Sound Design',
      'Podcast Editing',
      'Podcast Production',
      'Audio Editing',
      'Audio Mixing',
      'Audio Mastering',
      'Voice Over',
      'Voice Acting',
      'Narration',
      'Commercial Voice Over',
      'Audiobook Narration',
      'Character Voice',
      'IVR Recording',
      'DJ Drops',
      'Sound Effects',
      'Foley',
      'Audio Restoration',
      'Noise Removal',
      'Audio Transcription',
      'Singing',
      'Vocal Tuning',
      'Auto-Tune',
      'Melody Writing',
      'Lyrics Writing',
      'Music Arrangement',
      'Orchestration',
      'Film Scoring',
      'Game Audio',
      'MIDI Programming',
      'Ableton Live',
      'FL Studio',
      'Logic Pro',
      'Pro Tools',
      'GarageBand',
      'Cubase',
      'Adobe Audition',
      'Audacity',
      'Reaper',
      'Studio One',
      'Guitar',
      'Piano',
      'Drums',
      'Bass',
      'Synthesizer',
    ],
  },
  {
    id: 'programming-tech',
    name: 'Programming & Tech',
    icon: 'code',
    skills: [
      'Web Development',
      'Frontend Development',
      'Backend Development',
      'Full Stack Development',
      'Mobile App Development',
      'iOS Development',
      'Android Development',
      'Cross-Platform Development',
      'React Native',
      'Flutter',
      'React',
      'Vue.js',
      'Angular',
      'Next.js',
      'Nuxt.js',
      'Svelte',
      'JavaScript',
      'TypeScript',
      'HTML',
      'CSS',
      'Tailwind CSS',
      'Bootstrap',
      'SASS/SCSS',
      'Node.js',
      'Express.js',
      'NestJS',
      'Python',
      'Django',
      'Flask',
      'FastAPI',
      'Java',
      'Spring Boot',
      'Kotlin',
      'Swift',
      'Objective-C',
      'C#',
      '.NET',
      'ASP.NET',
      'C++',
      'C',
      'Go',
      'Rust',
      'Ruby',
      'Ruby on Rails',
      'PHP',
      'Laravel',
      'WordPress Development',
      'Shopify Development',
      'WooCommerce',
      'Magento',
      'Drupal',
      'Joomla',
      'Webflow',
      'Wix',
      'Squarespace',
      'API Development',
      'REST API',
      'GraphQL',
      'WebSocket',
      'Microservices',
      'Serverless',
      'AWS Lambda',
      'Cloud Functions',
      'Database Design',
      'SQL',
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'Firebase',
      'Prisma',
      'AWS',
      'Google Cloud',
      'Azure',
      'Docker',
      'Kubernetes',
      'CI/CD',
      'DevOps',
      'Git',
      'GitHub',
      'GitLab',
      'Cybersecurity',
      'Penetration Testing',
      'Network Security',
      'Blockchain',
      'Solidity',
      'Smart Contracts',
      'Web3',
      'NFT Development',
      'Game Development',
      'Unity',
      'Unreal Engine',
      'Godot',
      'Desktop Applications',
      'Electron',
      'QA Testing',
      'Automated Testing',
      'Manual Testing',
      'Selenium',
      'Cypress',
      'Jest',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    icon: 'briefcase',
    skills: [
      'Business Consulting',
      'Business Plan Writing',
      'Financial Planning',
      'Financial Analysis',
      'Financial Modeling',
      'Budgeting',
      'Forecasting',
      'Bookkeeping',
      'Accounting',
      'Tax Preparation',
      'Payroll',
      'QuickBooks',
      'Xero',
      'Project Management',
      'Agile',
      'Scrum',
      'Kanban',
      'Jira',
      'Asana',
      'Trello',
      'Monday.com',
      'Product Management',
      'Product Strategy',
      'Market Research',
      'Competitive Analysis',
      'Business Analysis',
      'Requirements Gathering',
      'Process Improvement',
      'Operations Management',
      'Supply Chain Management',
      'Inventory Management',
      'E-commerce Management',
      'Virtual Assistant',
      'Administrative Support',
      'Data Entry',
      'Customer Service',
      'Customer Support',
      'Technical Support',
      'Sales',
      'Lead Generation',
      'CRM Management',
      'Salesforce',
      'HubSpot CRM',
      'Zoho CRM',
      'Human Resources',
      'Recruiting',
      'Talent Acquisition',
      'Employee Training',
      'Legal Consulting',
      'Contract Review',
      'Presentation Design',
      'Pitch Deck Creation',
      'Investor Relations',
      'Startup Consulting',
      'Fundraising Strategy',
      'Event Planning',
      'Event Management',
    ],
  },
  {
    id: 'data-analytics',
    name: 'Data & Analytics',
    icon: 'chart',
    skills: [
      'Data Analysis',
      'Data Visualization',
      'Business Intelligence',
      'Data Science',
      'Machine Learning',
      'Deep Learning',
      'Artificial Intelligence',
      'Natural Language Processing',
      'Computer Vision',
      'Predictive Analytics',
      'Statistical Analysis',
      'Quantitative Analysis',
      'Data Mining',
      'Big Data',
      'Data Engineering',
      'ETL',
      'Data Warehousing',
      'Data Modeling',
      'Database Administration',
      'Python for Data Science',
      'R Programming',
      'SQL Analytics',
      'Excel',
      'Advanced Excel',
      'VBA',
      'Power BI',
      'Tableau',
      'Looker',
      'Google Data Studio',
      'Metabase',
      'Apache Spark',
      'Hadoop',
      'Snowflake',
      'Databricks',
      'dbt',
      'Pandas',
      'NumPy',
      'Scikit-learn',
      'TensorFlow',
      'PyTorch',
      'Keras',
      'SPSS',
      'SAS',
      'Stata',
      'MATLAB',
      'A/B Testing Analysis',
      'Cohort Analysis',
      'Customer Analytics',
      'Web Analytics',
      'Marketing Analytics',
      'Financial Analytics',
      'Healthcare Analytics',
      'Sports Analytics',
      'Geospatial Analysis',
      'Survey Design',
      'Survey Analysis',
      'Report Writing',
      'Dashboard Creation',
    ],
  },
  {
    id: 'photography',
    name: 'Photography',
    icon: 'camera',
    skills: [
      'Product Photography',
      'Portrait Photography',
      'Headshot Photography',
      'Fashion Photography',
      'Food Photography',
      'Real Estate Photography',
      'Architectural Photography',
      'Interior Photography',
      'Lifestyle Photography',
      'Event Photography',
      'Wedding Photography',
      'Concert Photography',
      'Sports Photography',
      'Nature Photography',
      'Wildlife Photography',
      'Landscape Photography',
      'Travel Photography',
      'Street Photography',
      'Documentary Photography',
      'Stock Photography',
      'Commercial Photography',
      'Advertising Photography',
      'Catalog Photography',
      'E-commerce Photography',
      'Amazon Product Photography',
      'Photo Editing',
      'Photo Retouching',
      'Portrait Retouching',
      'Product Retouching',
      'Background Removal',
      'Image Manipulation',
      'Photo Restoration',
      'Photo Colorization',
      'HDR Photography',
      'Composite Photography',
      'Photo Montage',
      'Adobe Lightroom',
      'Adobe Photoshop',
      'Capture One',
      'DxO PhotoLab',
      'Luminar',
      'Drone Photography',
      'Aerial Photography',
      '360 Photography',
      'Virtual Tour Photography',
      'Photo Book Design',
      'Photo Slideshow',
      'Photography Direction',
      'Styling',
      'Model Casting',
    ],
  },
  {
    id: 'lifestyle',
    name: 'Lifestyle',
    icon: 'heart',
    skills: [
      'Life Coaching',
      'Career Coaching',
      'Executive Coaching',
      'Business Coaching',
      'Health Coaching',
      'Fitness Coaching',
      'Nutrition Coaching',
      'Wellness Coaching',
      'Personal Training',
      'Yoga Instruction',
      'Meditation Instruction',
      'Mindfulness Training',
      'Relationship Coaching',
      'Dating Coaching',
      'Parenting Coaching',
      'Financial Coaching',
      'Personal Finance',
      'Astrology',
      'Tarot Reading',
      'Numerology',
      'Spiritual Guidance',
      'Personal Styling',
      'Fashion Consulting',
      'Wardrobe Styling',
      'Image Consulting',
      'Color Analysis',
      'Makeup Artistry',
      'Hair Styling',
      'Skincare Consulting',
      'Interior Decorating',
      'Home Organization',
      'Feng Shui',
      'Travel Planning',
      'Trip Planning',
      'Itinerary Planning',
      'Destination Research',
      'Travel Consulting',
      'Diet Planning',
      'Meal Planning',
      'Recipe Development',
      'Cooking Instruction',
      'Baking',
      'Wine Consulting',
      'Party Planning',
      'Wedding Planning',
      'Gift Selection',
      'Personal Shopping',
      'Pet Training',
      'Pet Care Consulting',
      'Gardening Consulting',
    ],
  },
  {
    id: 'ai-services',
    name: 'AI Services',
    icon: 'bot',
    skills: [
      'AI Consulting',
      'AI Strategy',
      'AI Implementation',
      'Machine Learning Development',
      'Deep Learning Development',
      'Neural Network Design',
      'AI Model Training',
      'AI Model Fine-tuning',
      'Prompt Engineering',
      'ChatGPT Integration',
      'GPT-4 Development',
      'Claude Integration',
      'Anthropic API',
      'OpenAI API',
      'LLM Development',
      'LLM Fine-tuning',
      'Conversational AI',
      'Chatbot Development',
      'Virtual Assistant Development',
      'AI Chatbot',
      'Voice Assistant Development',
      'Natural Language Processing',
      'Text Generation',
      'Text Classification',
      'Sentiment Analysis',
      'Named Entity Recognition',
      'Computer Vision',
      'Image Recognition',
      'Object Detection',
      'Image Generation',
      'DALL-E Integration',
      'Midjourney',
      'Stable Diffusion',
      'AI Art Generation',
      'AI Image Editing',
      'AI Video Generation',
      'AI Voice Generation',
      'Text-to-Speech',
      'Speech-to-Text',
      'Voice Cloning',
      'AI Music Generation',
      'AI Content Writing',
      'AI Copywriting',
      'AI Translation',
      'AI Data Analysis',
      'Predictive AI',
      'Recommendation Systems',
      'AI Automation',
      'RPA with AI',
      'AI Testing',
      'MLOps',
      'Model Deployment',
      'Hugging Face',
      'LangChain',
      'Vector Databases',
      'Pinecone',
      'Weaviate',
      'RAG Development',
      'AI Agents Development',
    ],
  },
];

/**
 * Get all skills as a flat array
 */
export const getAllSkills = (): string[] => {
  return SKILL_CATEGORIES.flatMap((category) => category.skills);
};

/**
 * Get skills by category ID
 */
export const getSkillsByCategory = (categoryId: string): string[] => {
  const category = SKILL_CATEGORIES.find((cat) => cat.id === categoryId);
  return category ? category.skills : [];
};

/**
 * Search skills across all categories
 */
export const searchSkills = (query: string, limit: number = 10): string[] => {
  if (!query || query.length < 2) return [];

  const lowerQuery = query.toLowerCase();
  const allSkills = getAllSkills();

  // First, get exact matches (starts with query)
  const exactMatches = allSkills.filter((skill) =>
    skill.toLowerCase().startsWith(lowerQuery)
  );

  // Then, get partial matches (contains query)
  const partialMatches = allSkills.filter(
    (skill) =>
      skill.toLowerCase().includes(lowerQuery) &&
      !skill.toLowerCase().startsWith(lowerQuery)
  );

  // Combine and limit results
  return [...exactMatches, ...partialMatches].slice(0, limit);
};

/**
 * Get category for a skill
 */
export const getCategoryForSkill = (skillName: string): SkillCategory | null => {
  const lowerSkill = skillName.toLowerCase();

  for (const category of SKILL_CATEGORIES) {
    if (category.skills.some((skill) => skill.toLowerCase() === lowerSkill)) {
      return category;
    }
  }

  return null;
};

/**
 * Check if a skill exists in any category
 */
export const isValidSkill = (skillName: string): boolean => {
  return getCategoryForSkill(skillName) !== null;
};
